const Actions = {
    'LOAD_TRADES':'LOAD_TRADES',
    'FETCH_TRADES':'FETCH_TRADES',
    'UPDATE_TRADE':'UPDATE_TRADE',
    'DELETE_TRADE':'DELETE_TRADE',
    'SET_SEARCH_CRITERIA': 'SET_SEARCH_CRITERIA'
}

module.exports = Actions;