const Actions = {
    'LOAD_TRADES':'LOAD_TRADES',
    'FETCH_TRADES':'FETCH_TRADES',
    'UPDATE_TRADE':'UPDATE_TRADE',
    'DELETE_TRADE':'DELETE_TRADE',
    'EDIT_TRADE':'EDIT_TRADE',
    'DEFAULT_EDIT_TRADE':'DEFAULT_EDIT_TRADE',
    'SELECT_TRADE':'SELECT_TRADE',
    'LOAD_SEARCH_CRITERIA': 'LOAD_SEARCH_CRITERIA',
    'SET_ACTIVE_SEARCH_CRITERIA': 'SET_ACTIVE_SEARCH_CRITERIA'
}

module.exports = Actions;